include: package:lints/recommended.yaml

analyzer:
  exclude:
    - frontend/**

linter:
  rules:
    prefer_single_quotes: true
    sort_pub_dependencies: true
    implicit_call_tearoffs: false
    unawaited_futures: true
