name: aoc
description: Advent of Code 2024 solutions
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.6.0

workspace:
  - packages/core
  - packages/day_builder

dependencies:
  aoc_core:
    path: packages/core
  args: ^2.4.2
  async: ^2.11.0
  dotenv: ^4.2.0
  logger: ^2.0.0
  memoized: ^2.0.0
  meta: ^1.0.0
  minio: ^3.5.7
  squadron: ^6.0.0

dev_dependencies:
  build_runner: ^2.4.0
  day_builder:
    path: packages/day_builder
  lints: ^5.0.0
  squadron_builder: ^6.0.0
  test: ^1.0.0
