name: aoc
description: Advent of Code 2024 solutions
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  args: ^2.4.2
  async: ^2.11.0
  collection: ^1.18.0
  day_part:
    path: day_part
  logger: ^2.0.0
  memoized: ^2.0.0
  meta: ^1.0.0

dev_dependencies:
  build_runner: ^2.4.0
  day_builder:
    path: day_builder
  lints: ^5.0.0
  test: ^1.0.0
