name: Workflow
on:
  push:
    branches: [ main ]
  pull_request: { }

jobs:
  validate-renovate-config:
    name: Validate Renovate configuration
    uses: BlindfoldedSurgery/renovate-config/.github/workflows/validate.yml@main

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - name: Get dependencies
        run: dart pub get --enforce-lockfile
      - name: Generate code
        run: dart run build_runner build
      - name: Run tests
        run: dart test

  check-format:
    name: Check Format
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - name: Check formatting
        run: dart format bin lib test day_builder/lib core/lib --set-exit-if-changed

  lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir:
          - .
          - core
          - day_builder
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - name: Get dependencies
        run: dart pub get --enforce-lockfile
        working-directory: ${{ matrix.dir }}
      - name: Generate code
        run: dart run build_runner build
        if: matrix.dir == '.'
        working-directory: ${{ matrix.dir }}
      - name: Run Analysis
        run: dart analyze --fatal-infos
        working-directory: ${{ matrix.dir }}

  build:
    name: Build Binary
    needs:
      - validate-renovate-config
      - test
      - check-format
      - lint
    strategy:
      fail-fast: false
      matrix:
        include:
          - id: linux-amd64
            runner: ubuntu-latest
          - id: linux-arm64
            runner: ubicloud-standard-2-arm
          - id: macos-amd64
            runner: macos-latest
          - id: win-amd64
            runner: windows-latest
            filename: advent.exe
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          # renovate: datasource=docker depName=dart
          sdk: 3.5.4
      - run: |
          dart pub get --enforce-lockfile
          dart run build_runner build
          mkdir output
      - run: dart compile exe bin/main.dart -o "output/${{ matrix.filename || 'advent' }}"
      - if: matrix.runner != 'windows-latest'
        run: chmod +x "output/${{ matrix.filename || 'advent' }}"
      - uses: actions/upload-artifact@v4
        if: github.ref_name == github.event.repository.default_branch
        with:
          name: binary-${{ matrix.id }}
          path: output/*

  build-result:
    name: Binaries Built
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - run: echo "Builds were successful"
